common:
  debug:           true
  AppSecret:     sfdsfdsfscc&234*21
  template_path:

  HttpPort:       8008
  ReadTimeout:    30
  WriteTimeout:   30
  PageSize:       100

mysql:
  dbtype: mysql
  host: localhost
  username: zs
  password: zs
  port: 3306
  dbname: go_ops
  prefix: ops

pgsql:
  dbtype: postgresql
  host: 127.0.0.1
  username: zs
  password: zs
  port: 3306
  dbname: ops
  prefix: ops



cache:
  host: localhost:6379
  password :
  dbname: 4

jwt:
  SECRET: session
  EXP:    3600
  ALG:    HS256

cokkie:
  name: cokkie


email:
  host:
  password:
  user:
  admin:
